// NE ACTİON OLACAKSA BURAYA YAZ 1. ADIM BURASI
export const INCREASE_COUNTER="INCREASE_COUNTER" 
export const DECREASE_COUNTER="DECREASE_COUNTER"
export const DECREASE_BY_TWO_COUNTER="DECREASE_BY_TWO_COUNTER"